Update to latest from build 10.7.0.0.133 (IFS 10.7.0.0.145)

diff --git a/ShmemApps/apps/prepare_run b/ShmemApps/apps/prepare_run
--- a/ShmemApps/apps/prepare_run
+++ b/ShmemApps/apps/prepare_run
@@ -1,7 +1,7 @@
 #!/bin/sh
 # BEGIN_ICS_COPYRIGHT8 ****************************************
 # 
-# Copyright (c) 2015, Intel Corporation
+# Copyright (c) 2015-2017, Intel Corporation
 # 
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions are met:
@@ -34,27 +34,30 @@
 
 # this script should be . included in a run_ script
 # Input:
-#   MPICH_PREFIX  - path to MPICH tools
-#   MPI_HOSTS  - mpi_hosts file to use (default is $PWD/mpi_hosts)
-#   SHOW_MPI_HOSTS - set to "y" if MPI_HOSTS contents should be output prior
-#                    to starting job.  Set to "n" to disable
-#                    defaults to "y"
+#   MPICH_PREFIX    - path to MPICH tools
+#   MPI_HOSTS       - mpi_hosts file to use (default is $PWD/mpi_hosts)
+#   SHOW_MPI_HOSTS  - set to "y" if MPI_HOSTS contents should be output prior
+#                     to starting job.  Set to "n" to disable
+#                     defaults to "y"
 #   SHOW_MPI_HOSTS_LINES - maximum lines in MPI_HOSTS to show.  Default is 128
-#                    Only lines applicable to job will be shown.
-#                    Note the file might include some comment lines
-#   NUM_PROCESSES - number of processes in job, if "" no count is specified
-#                if "all" use wc -l $MPI_HOSTS as the process count
-#   LOGFILE - logfile to append results of run to, if "" this script will define
-#   LOGSUFFIX - suffix to append to logfile name defined by this script
-# Output:
-#   MPIRUN_CMD - MPI command to start job, actual program name and args can be suffixed
+#                          Only lines applicable to job will be shown.
+#                          Note the file might include some comment lines
+#   NUM_PROCESSES   - number of processes in job, if "" no count is specified
+#                     if "all" use wc -l $MPI_HOSTS as the process count
+#   LOGFILE         - logfile to append results of run to, if ""
+#                     this script will define
+#   LOGSUFFIX       - suffix to append to logfile name defined by this script
+SOS_RPM=sandia-openshmem_gcc_hfi
+SOS_TEST_RPM=sandia-openshmem_gcc_hfi-tests
 
 get_shmem_bench_dir()
 {
-	local instDir=`rpm -q --queryformat="%{INSTFILENAMES}" shmem-benchmarks_gcc_hfi`
+
+    local TEST_NAME=$1
+    local instDir=`rpm -ql $SOS_TEST_RPM |grep -e "/$TEST_NAME$" |sed -e "s%/$TEST_NAME%%"`
 	if [[ $? -ne 0 || $instDir = "(none)" || ! -d $instDir ]] ; then
-		echo "Warning: shmem-benchmarks dir could not be determined via rpm" >&2
-		instDir="/usr/shmem/gcc/openshmem-1.0h-hfi/tests/shmem-benchmarks"
+        echo "$TEST_NAME not found"
+        exit 1
 	fi
 	echo $instDir
 }
@@ -62,11 +65,6 @@ get_shmem_bench_dir()
 show_mpi_hosts()
 {
 	local lines
-
-	if [[ -z $MPI_HOSTS ]] ; then
-		echo "No MPI hosts file defined"
-		return 0
-	fi
 
 	echo "Using hosts list: $MPI_HOSTS"
 
@@ -95,6 +93,15 @@ show_mpi_hosts()
 	fi
 }
 
+
+if [ -z "$NUM_PROCESSES" ]; then
+    NUM_PROCESSES=2
+    echo " Defaulting to $NUM_PROCESSES processes"
+elif [[ ! "$NUM_PROCESSES" =~ [0-9]+ ]]; then
+    echo " Expected number for <number_of_processes> and got: $NUM_PROCESSES"
+    exit 1
+fi
+
 if [ -z "$LOGFILE" ]
 then
 	CURTIME=`date +%d%b%y%H%M%S`
@@ -107,20 +114,23 @@ then
 	echo " logfile $LOGFILE"
 	> $LOGFILE
 fi
+SHMEM_PREFIX=${SHMEM_PREFIX:-`rpm -ql $SOS_RPM |grep -e "bin/oshrun" |sed -e "s%/bin/oshrun%%"`}
+if [ -z "$SHMEM_PREFIX" ]; then
+     echo "Environment variale SHMEM_PREFIX Not defined" >&2
+fi
 
-SHMEM_PREFIX=${SHMEM_PREFIX:-`pkg-config --variable=prefix openshmem`}
-SHMEM_PREFIX=${SHMEM_PREFIX:-/usr/shmem/gcc/openshmem-1.0h-hfi}	# default SHMEM_PREFIX
-export SHMEM_RUN=$SHMEM_PREFIX/bin/oshrun
-
-if [[ ! -e $SHMEM_RUN ]] ; then
-	echo "$SHMEM_RUN: Not found" >&2
+OSHRUN=$SHMEM_PREFIX/bin/oshrun
+if [[ ! -e $OSHRUN ]] ; then
+	echo "osrun Not found. Expecting it at: $OSHRUN " >&2
 	exit 1
 fi
 
-OPENSHMEM_PREFIX=${OPENSHMEM_PREFIX:-`pkg-config --variable=prefix openshmem`}
-OPENSHMEM_PREFIX=${OPENSHMEM_PREFIX:-/usr/shmem/gcc/openshmem-1.0h-hfi}
-GASNET_PREFIX=${GASNET_PREFIX:-/usr/shmem/gcc/gasnet-1.24.0-openmpi-hfi}
 export MPI_HOSTS=${MPI_HOSTS:-./shmem_hosts}
+
+if [ ! -f $MPI_HOSTS ] ; then
+    echo "No MPI hosts file defined. Set MPI_HOSTS variable pointing to the hosts file"
+    exit 1
+fi
 
 if [[ -z $MPICH_PREFIX ]] ; then
 	. ./select_mpi
@@ -128,11 +138,16 @@ if [[ -z $MPICH_PREFIX ]] ; then
 		echo "Error: MPICH_PREFIX not set" >&2
 		exit 1
 	fi
+    echo " Using MVAPICH2 at $MPICH_PREFIX  (in PATH and LD_LIBRARY_PATH)" >&2
 fi
 
-export PATH=${MPICH_PREFIX}/bin:${PATH}
-export LD_LIBRARY_PATH=${MPICH_PREFIX}/lib64:${LD_LIBRARY_PATH}
+rpm -q $SOS_TEST_RPM &>/dev/null
+if [ $? -ne 0 ]; then
+    echo "Error: RPM $SOS_TEST_RPM is expected to be installed with the tests binaries"
+    exit 1
+fi
 
-export PATH=${OPENSHMEM_PREFIX}/bin:${GASNET_PREFIX}/bin:${PATH}
-export LD_LIBRARY_PATH=${OPENSHMEM_PREFIX}/lib:${GASNET_PREFIX}/lib:${LD_LIBRARY_PATH}
-export MPIRUN_CMD="mpirun --map-by node -np %N -mca pml ob1 -mca btl tcp,sm,self -mca plm_rsh_no_tree_spawn 1 --allow-run-as-root --hostfile $MPI_HOSTS %P %A"
+export SHMEM_RUN="$SHMEM_PREFIX/bin/oshrun --hostfile $MPI_HOSTS"
+export PATH=${MPICH_PREFIX}/bin:${SHMEM_PREFIX}/bin:${PATH}
+export LD_LIBRARY_PATH=${MPICH_PREFIX}/lib64:${SHMEM_PREFIX}/lib64:${LD_LIBRARY_PATH}
+
